import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#09090b',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },

  premiumTimelineCard: {
    backgroundColor: '#18181b',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#27272a',
  },
  timelineStationName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#fafafa',
  },
  pfBadgeSmall: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  pfBadgeTextSmall: {
    color: '#60a5fa',
    fontSize: 10,
    fontWeight: '800',
  },
  delayBadgeSmall: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  delayBadgeTextSmall: {
    color: '#ef4444',
    fontSize: 10,
    fontWeight: '800',
  },
  timeLabelSmall: {
    color: '#52525b',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  timeValueSmall: {
    color: '#fafafa',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 4,
  },
  timeSubSmall: {
    color: '#3f3f46',
    fontSize: 10,
    marginTop: 2,
  },
  permissionCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashIcon: {
    alignItems: 'center',
    marginBottom: 16,
  },
  splashEmoji: {
    fontSize: 56,
  },
  splashTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#fafafa',
    textAlign: 'center',
    marginBottom: 8,
  },
  splashSub: {
    fontSize: 14,
    color: '#71717a',
    textAlign: 'center',
  },

  // ── Permission Screen ──
  permissionScreen: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 60,
    paddingBottom: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  permIconWrapper: {
    width: 120,
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  permIconBg: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#1e1b4b',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
  permIconRing: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: '#6366f1',
    borderStyle: 'dashed',
    position: 'absolute',
    opacity: 0.6,
  },
  permIconEmoji: {
    fontSize: 44,
  },
  permTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#fafafa',
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: -0.5,
  },
  permDesc: {
    fontSize: 15,
    color: '#a1a1aa',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 28,
  },
  featChips: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 28,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  featureChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#27272a',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 100,
  },
  featureChipIcon: {
    fontSize: 14,
  },
  featureChipLabel: {
    fontSize: 13,
    color: '#a1a1aa',
    fontWeight: '500',
  },
  privacyNote: {
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#27272a',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 32,
    width: '100%',
  },
  privacyText: {
    fontSize: 12,
    color: '#71717a',
    textAlign: 'center',
    lineHeight: 18,
  },
  permButtons: {
    width: '100%',
    gap: 12,
    marginBottom: 32,
  },
  permBtn: {
    width: '100%',
  },
  permBtnPrimary: {
    ...Platform.select({
      web: {
        boxShadow: '0 4px 12px rgba(99, 102, 241, 0.4)',
      },
      default: {
        shadowColor: '#6366f1',
        shadowOpacity: 0.4,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 12,
        elevation: 6,
      }
    })
  },
  appBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#18181b',
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#27272a',
  },
  appBadgeText: {
    fontSize: 12,
    color: '#52525b',
    fontWeight: '500',
  },

  // ── Confirmation Modal Styles ──
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmContent: {
    width: '90%',
    maxWidth: 500,
    backgroundColor: '#09090b',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#27272a',
    alignItems: 'center',
  },
  confirmIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  confirmTitle: {
    color: '#fafafa',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
  },
  confirmMessage: {
    color: '#71717a',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  confirmActionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  confirmCancelBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#18181b',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#27272a',
  },
  confirmCancelText: {
    color: '#fafafa',
    fontWeight: '600',
  },
  confirmBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmBtnText: {
    color: '#fff',
    fontWeight: '700',
  },

  // ── Admin Panel / Drawer Styles ──
  exitAdminBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#450a0a',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: '#ef444433',
  },
  exitAdminText: {
    color: '#ef4444',
    fontSize: 12,
    fontWeight: '700',
  },
  stationActionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  stationViewBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#27272a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stationEditBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#1e1b4b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stationDeleteBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#450a0a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelEditBtn: {
    marginTop: 12,
    alignItems: 'center',
    padding: 10,
  },
  cancelEditText: {
    color: '#71717a',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  authModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  authModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.85)',
  },
  authModalContent: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: '#09090b',
    borderRadius: 24,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#27272a',
    ...Platform.select({
      web: { boxShadow: '0 20px 40px rgba(0,0,0,0.6)' },
      default: { elevation: 10 }
    })
  },
  authModalHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  authModalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#fafafa',
    marginTop: 12,
    letterSpacing: 2,
  },
  authModalSub: {
    fontSize: 13,
    color: '#71717a',
    marginTop: 4,
  },
  passcodeContainer: {
    width: '100%',
    marginBottom: 24,
  },
  passcodeInput: {
    width: '100%',
    height: 60,
    backgroundColor: '#18181b',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#27272a',
    color: '#fff',
    fontSize: 32,
    textAlign: 'center',
    letterSpacing: 10,
    fontWeight: '700',
  },
  authCancelBtn: {
    padding: 10,
  },
  authCancelText: {
    color: '#71717a',
    fontSize: 14,
    fontWeight: '600',
  },

  // ── Drawer Styles ──
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    flexDirection: 'row',
  },
  drawerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  drawerContent: {
    width: '85%',
    maxWidth: 450,
    backgroundColor: '#09090b',
    height: '100%',
    borderRightWidth: 1,
    borderRightColor: '#27272a',
    ...Platform.select({
      web: { boxShadow: '10px 0 30px rgba(0,0,0,0.5)' },
      default: { elevation: 20 }
    })
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#18181b',
  },
  drawerTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 2,
  },
  drawerTabs: {
    flexDirection: 'row',
    padding: 20,
    gap: 12,
  },
  drawerTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#27272a',
  },
  drawerTabActive: {
    backgroundColor: '#6366f1',
    borderColor: '#818cf8',
  },
  drawerTabText: {
    fontSize: 13,
    color: '#71717a',
    fontWeight: '700',
  },
  drawerTabTextActive: {
    color: '#fff',
  },
  menuBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#27272a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stationListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#18181b',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#27272a',
    marginBottom: 8,
  },
  stationListLeft: {
    flex: 1,
    gap: 4,
  },
  stationListCode: {
    fontSize: 14,
    fontWeight: '900',
    color: '#818cf8', // Bright indigo
    letterSpacing: 1,
  },
  stationListName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fafafa',
  },
  stationListSub: {
    fontSize: 12,
    color: '#a1a1aa', // Bright zinc
    marginTop: 2,
  },
  stationListMeta: {
    fontSize: 11,
    color: '#71717a',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  // ── Admin Form Styles ──
  inputGroup: {
    marginBottom: 10,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#71717a',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  inputWrapper: {
    backgroundColor: '#09090b',
    borderWidth: 1,
    borderColor: '#27272a',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 44,
    justifyContent: 'center',
  },
  nativeInput: {
    color: '#fff',
    fontSize: 14,
    height: '100%',
  },
  fetchBtn: {
    backgroundColor: '#27272a',
    paddingHorizontal: 15,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3f3f46',
  },
  fetchBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  saveBtn: {
    backgroundColor: '#6366f1',
    height: 48,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  saveBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },

  // ── Main Screen ──
  scroll: { flex: 1 },
  content: { padding: 16, gap: 16 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  headerLeft: { gap: 2 },
  headerRight: { alignItems: 'flex-end', gap: 6 },
  appTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fafafa',
    letterSpacing: -0.5,
  },
  appSubtitle: {
    fontSize: 13,
    color: '#71717a',
    fontWeight: '400',
  },
  locationGrantedPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#14532d',
    borderWidth: 1,
    borderColor: '#16a34a',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 100,
  },
  greenDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4ade80',
  },
  locationGrantedText: {
    fontSize: 11,
    color: '#4ade80',
    fontWeight: '600',
  },
  card: { marginBottom: 0 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#a1a1aa',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  subSectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#71717a',
    letterSpacing: 1,
    marginTop: 12,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  liveDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  statusBanner: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    marginBottom: 16,
  },
  statusText: { fontSize: 18, fontWeight: '700' },
  distanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  distanceLabel: { fontSize: 14, color: '#a1a1aa' },
  stationNameInline: { fontSize: 14, color: '#fafafa', fontWeight: '600' },
  distanceValue: { fontSize: 14, color: '#6366f1', fontWeight: '700' },
  thresholdInfo: { gap: 4 },
  thresholdText: { fontSize: 12, color: '#71717a' },
  thresholdValue: { color: '#a1a1aa', fontWeight: '600' },
  intervalText: { fontSize: 12, color: '#71717a' },
  intervalValue: { color: '#6366f1', fontWeight: '600' },
  stationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    marginBottom: 4,
  },
  stationInfo: { flex: 1, gap: 4 },
  stationName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#fafafa',
    letterSpacing: -0.3,
  },
  stationCode: {
    fontSize: 13,
    color: '#71717a',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontWeight: '500',
  },
  badgeRow: { flexDirection: 'row', gap: 6, marginTop: 4 },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  detailItem: { width: '45%', gap: 2 },
  detailLabel: {
    fontSize: 11,
    color: '#71717a',
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailValue: { fontSize: 14, color: '#fafafa', fontWeight: '600' },
  distanceBig: { alignItems: 'center', paddingVertical: 8, gap: 4 },
  distanceBigLabel: {
    fontSize: 12,
    color: '#71717a',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  distanceBigValue: { fontSize: 40, fontWeight: '800', letterSpacing: -1 },
  distanceBigSub: { fontSize: 13, color: '#a1a1aa' },
  coordRow: { flexDirection: 'row', alignItems: 'center' },
  coordItem: { flex: 1, gap: 4 },
  coordDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#27272a',
    marginHorizontal: 16,
  },
  coordLabel: {
    fontSize: 11,
    color: '#71717a',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  coordValue: {
    fontSize: 15,
    color: '#fafafa',
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  lastChecked: {
    fontSize: 12,
    color: '#52525b',
    marginTop: 12,
    textAlign: 'right',
  },
  errorTitle: { fontSize: 16, fontWeight: '700', color: '#f87171', marginBottom: 8 },
  errorText: { fontSize: 13, color: '#a1a1aa', lineHeight: 20 },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 6,
  },
  infoIcon: { fontSize: 16, width: 24 },
  infoText: { flex: 1, fontSize: 14, color: '#a1a1aa', lineHeight: 20 },

  // ── Live Board ──────────────────────────────────────────────────────────────
  liveBoardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#27272a',
    gap: 8,
  },
  liveBoardLeft: {
    flex: 1,
    gap: 3,
  },
  liveBoardTrainNum: {
    fontSize: 15,
    fontWeight: '800',
    color: '#fafafa',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },

  // ── Bottom Nav Bar ────────────────────────────────────────────────────────
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 80,
    backgroundColor: 'rgba(9, 9, 11, 0.85)',
    borderTopWidth: 1,
    borderTopColor: '#27272a',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 20, // For home indicator
    backdropFilter: 'blur(10px)',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navIcon: {
    fontSize: 22,
    marginBottom: 4,
    opacity: 0.5,
  },
  navIconActive: {
    opacity: 1,
  },
  navText: {
    fontSize: 10,
    color: '#71717a',
    fontWeight: '600',
  },
  navTextActive: {
    color: '#fafafa',
  },

  // ── Minimal Premium UI Additions ──────────────────────────────────────────
  tabContent: {
    flex: 1,
    gap: 16,
    paddingTop: 8,
  },
  premiumCard: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  premiumHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  premiumIcon: {
    fontSize: 24,
    marginRight: 8,
  },
  premiumTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#10b981',
  },
  premiumText: {
    fontSize: 15,
    color: '#e4e4e7',
    lineHeight: 22,
    marginBottom: 16,
  },
  boldText: {
    fontWeight: '800',
    color: '#fff',
  },
  premiumButton: {
    backgroundColor: '#10b981',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  premiumButtonText: {
    color: '#000',
    fontWeight: '700',
    fontSize: 15,
  },
  actionContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  mainActionButton: {
    width: 200,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  mainActionStart: {
    backgroundColor: '#fff',
  },
  mainActionStop: {
    backgroundColor: '#27272a',
    borderWidth: 1,
    borderColor: '#3f3f46',
  },
  mainActionText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000',
  },
  statusMinimalText: {
    fontSize: 13,
    color: '#a1a1aa',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  statusMinimalWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#27272a',
    marginTop: 8,
  },
  minimalCard: {
    backgroundColor: '#1c1c1e',
    borderRadius: 20,
    padding: 20,
  },
  minimalLabel: {
    fontSize: 11,
    color: '#71717a',
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 8,
  },
  minimalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  minimalValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fff',
  },
  minimalSub: {
    fontSize: 13,
    color: '#a1a1aa',
    marginTop: 2,
  },
  minimalRight: {
    alignItems: 'flex-end',
  },
  minimalDistance: {
    fontSize: 28,
    fontWeight: '800',
    color: '#818cf8',
    letterSpacing: -0.5,
  },
  minimalStatus: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  minimalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  trainRowMinimal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#27272a',
  },
  trainRowLeft: {
    flex: 1,
  },
  trainRowRight: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  trainViewBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#27272a',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  trainNumText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
  trainDestText: {
    fontSize: 13,
    color: '#a1a1aa',
    marginTop: 2,
  },
  trainTimeText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
  trainDelayText: {
    fontSize: 12,
    color: '#f59e0b',
    fontWeight: '600',
    marginTop: 2,
  },
  moreText: {
    fontSize: 13,
    color: '#6366f1',
    textAlign: 'center',
    marginTop: 12,
    fontWeight: '600',
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  historyIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  historyInfo: {
    flex: 1,
  },
  historyTrain: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  historyRoute: {
    color: '#71717a',
    fontSize: 11,
    marginTop: 2,
  },
  historyMeta: {
    alignItems: 'flex-end',
  },
  historyDate: {
    color: '#10b981',
    fontSize: 10,
    fontWeight: '700',
  },
  historyTime: {
    color: '#3f3f46',
    fontSize: 10,
    marginTop: 2,
  },
  emptyText: {
    fontSize: 14,
    color: '#a1a1aa',
    fontStyle: 'italic',
    paddingVertical: 10,
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    backgroundColor: '#18181b',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#27272a',
    borderStyle: 'dashed',
  },
  errorTextMinimal: {
    color: '#ef4444',
    fontSize: 13,
    marginBottom: 8,
  },
  confirmationButtons: {
    flexDirection: 'row',
    marginTop: 15,
  },
  debugRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  debugText: {
    fontSize: 13,
    color: '#a1a1aa',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    marginBottom: 4,
  },

  liveBoardTrainName: {
    fontSize: 13,
    color: '#d4d4d8',
    fontWeight: '600',
  },
  liveBoardRoute: {
    fontSize: 12,
    color: '#71717a',
  },
  liveBoardRight: {
    alignItems: 'flex-end',
    gap: 3,
    minWidth: 100,
  },
  liveBoardTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  liveBoardTimeLabel: {
    fontSize: 11,
    color: '#52525b',
    width: 24,
    fontWeight: '600',
  },
  liveBoardTime: {
    fontSize: 13,
    color: '#a1a1aa',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontWeight: '600',
  },
  liveBoardPlatform: {
    fontSize: 11,
    color: '#6366f1',
    fontWeight: '700',
    backgroundColor: '#1e1b4b',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  liveBoardStatus: {
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  liveBoardDelay: {
    fontSize: 11,
    color: '#fb923c',
    fontWeight: '600',
  },
  liveBoardError: {
    paddingVertical: 12,
  },

  // ── Speedometer Styles ──
  speedCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingVertical: 20,
  },
  speedValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginVertical: 10,
  },
  speedValueMain: {
    fontSize: 92,
    fontWeight: '800',
    color: '#10b981',
    fontVariant: ['tabular-nums'],
    letterSpacing: -2,
  },
  speedUnit: {
    fontSize: 20,
    fontWeight: '700',
    color: '#71717a',
    marginLeft: 8,
    letterSpacing: 1,
  },
  speedIndicatorBar: {
    width: '80%',
    height: 6,
    backgroundColor: '#27272a',
    borderRadius: 3,
    marginTop: 20,
    overflow: 'hidden',
  },
  speedIndicatorFill: {
    height: '100%',
    backgroundColor: '#10b981',
    borderRadius: 3,
  },
  accuracyNote: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 20,
    gap: 6,
  },
  accuracyText: {
    fontSize: 12,
    color: '#10b981',
    fontWeight: '600',
  },
  speedDisclaimer: {
    marginTop: 25,
    color: '#52525b',
    fontSize: 12,
    textAlign: 'center',
    paddingHorizontal: 30,
    lineHeight: 18,
  },

  // ── Intro Styles ──
  introContainer: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  introImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  introTrain: {
    position: 'absolute',
    width: 600,
    height: 300,
    bottom: 50,
  },
  fogOverlay: {
    position: 'absolute',
    top: 0,
    left: -200,
    width: '200%',
    height: '100%',
  },
  fogCloud: {
    width: 400,
    height: 400,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 200,
  },
  introOverlay: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  introTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
    ...Platform.select({
      web: {
        textShadow: '0 2px 10px rgba(0,0,0,0.75)'
      }
    })
  },
  introLine: {
    width: 60,
    height: 3,
    backgroundColor: '#10b981',
    marginVertical: 15,
    borderRadius: 2,
  },
  introSub: {
    fontSize: 12,
    color: '#10b981',
    fontWeight: '700',
    letterSpacing: 4,
    textTransform: 'uppercase',
  },
});
